image: Visual Studio 2017
platform: x64

environment:
  CONDA_PREFIX: C:\Miniconda36-x64
  PLAIDML_DEVICE_IDS: opencl_cpu.0
  PLAIDML_EXPERIMENTAL: 1

install:
  - cmd: if not exist opencl_runtime_16.1.2_x64_setup.msi appveyor DownloadFile http://registrationcenter-download.intel.com/akdlm/irc_nas/12512/opencl_runtime_16.1.2_x64_setup.msi
  - cmd: msiexec /i opencl_runtime_16.1.2_x64_setup.msi /qn /quiet /norestart
  - cmd: PATH=C:\Miniconda36-x64;C:\Miniconda36-x64\Scripts;C:\Miniconda36-x64\Library\bin;%PATH%
  - cmd: conda install -y -c conda-forge protobuf numpy
  - cmd: pip install "setuptools>=39"
  - cmd: pip install plaidml-keras onnx-plaidml

build_script:
  - cmd: rm BUILD && python setup.py install --force

test_script:
  - cmd: cd C:\projects
  - cmd: plaidbench -n 128 keras mobilenet
  - cmd: plaidbench -n 128 onnx squeezenet

cache:
  - opencl_runtime_16.1.2_x64_setup.msi
  - '%USERPROFILE%\.onnx'
