language: python
os:
  - linux
  # - osx ren-eable once before install is right for osx
python:
  - "2.7"
  - "3.5"
  - "3.6"

before_install:
  - echo "deb [arch=amd64] http://storage.googleapis.com/bazel-apt stable jdk1.8" | sudo tee /etc/apt/sources.list.d/bazel.list
  - curl https://bazel.build/bazel-release.pub.gpg | sudo apt-key add -
  - sudo apt-get update -q   
  - sudo apt-get install openjdk-8-jdk bazel bison g++ wget -y
  - wget https://storage.googleapis.com/external_build_repo/opencl_runtime_16.1.1_x64_ubuntu_6.4.0.25.tgz
  - tar xzvf opencl_runtime_16.1.1_x64_ubuntu_6.4.0.25.tgz
  - pushd opencl_runtime_16.1.1_x64_ubuntu_6.4.0.25
  - sudo ./install.sh --cli-mode --silent ../.intel-ocl-silent
  - popd

install:
  - pip install -r requirements.txt

script:
  - PLAIDML_EXPERIMENTAL=1 python plaidbench.py mobilenet
